aws_region: "{{ lookup('env', 'AWS_REGION') | default('us-east-1') }}"
ansible_aws_ssm_region: "{{ aws_region }}"
ansible_aws_ssm_bucket_name: "{{ lookup('env', 'ANSIBLE_SSM_BUCKET') | default('') }}"
ansible_aws_ssm_bucket_region: "{{ aws_region }}"
